### ISSUE TITLE
Some questions about the project name and logo

### ISSUE THREAD

**Issue by lsbbd** [Hgwxxdd/ladder-ui#1]
@Hgwxxdd  Hello~ I am glad to see that a new vue3 UI framework is under development.

I want to know why the project is called ladder-UI and where the inspiration for the logo comes from

**Comment by Hgwxxdd** [comment]
> @Hgwxxdd Hello~ I am glad to see that a new vue3 UI framework is under development.
> 
> I want to know why the project is called ladder-UI and where the inspiration for the logo comes from

@lsbbd  Hello !  I am glad to see your question.

1.  The name is just like the name. 
2. This logo is currently inspired by a web image and I hope to redesign it in the future.
